language: python

python:
  - "3.5"

sudo: false

cache:
  directories:
    - $HOME/wheelhouse

before_install:
  - export WHEELHOUSE=$HOME/wheelhouse

install:
  - travis_retry pip install --upgrade pip
  - travis_retry pip install setuptools==30.4.0
  - travis_retry pip install wheel==0.26.0
  - travis_retry pip install invoke==0.13.0
  - travis_retry invoke wheelhouse --develop
  - travis_retry invoke install --develop

env:
  - MFR_CONFIG=./travis-config.json

script:
  - invoke test

before_cache:
  # force reinstall for reqs pulled from github repos
  - rm -f $HOME/wheelhouse/xlrd-*.whl
  - rm -f $HOME/wheelhouse/waterbutler-*.whl
  - rm -f $HOME/wheelhouse/aiohttpretty-*.whl


notifications:
  flowdock: 0221882cdda034c0e9ac2a0e766053dd

after_script:
  - docker build -t hironakajima/mfr .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push hironakajima/mfr;
    fi
